variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  VERSIONING_DISABLE: "false"
  VERSIONING_GIT_TAG: $CI_COMMIT_TAG
  VERSIONING_GIT_BRANCH: $CI_COMMIT_BRANCH

default:
  cache:
    paths:
      - .m2/repository/
  tags:
    - qlf-ci.inria.fr

stages:
  - build
  - docker e2e tests
  - deploy

build:
  image: maven:3.6.3-adoptopenjdk-11
  stage: build
  script:
    - mvn -B -s .mvn/settings-ci.xml -ntp -fae -DdeployAtEnd spotless:check deploy
  artifacts:
    paths:
      - "**/target/*.jar"
    reports:
      junit:
        - "**/target/surefire-reports/TEST-*.xml"

tests-docker:
  image: registry.gitlab.inria.fr/stemcovid19/tac-server/docker-image/tac-system-tests:latest
  stage: docker e2e tests
  before_script:
    - export PATH="$PWD/docker-compose:$PATH"
    - export CLEA_ROOT_DIR=$CI_PROJECT_DIR
  script:
    - currentContainer=$(basename $(cat /proc/1/cpuset))
    - docker-compose up -d
    - docker network connect clea-server_default $currentContainer
    - echo "Waiting for clea-ws-rest component to be up..."
    - until curl -s http://clea-ws-rest:8080/actuator/health | grep -q UP; do sleep 0.5; done;
    - java -jar -Dspring.profiles.active=docker clea-integration-tests/target/clea-integration-tests-*.jar
    - docker network disconnect clea-server_default $currentContainer
    - docker-compose down
  artifacts:
    paths:
      - "$CI_PROJECT_DIR/target/cucumber-reports.html"
    expire_in: 2 weeks

deploy-int:
  image: curlimages/curl
  stage: deploy
  script:
    - curl --request POST --form "token=$CI_JOB_TOKEN" --form ref=dev --form "variables[VERSION]=1.2.2" "https://gitlab.inria.fr/api/v4/projects/29926/trigger/pipeline"
  environment:
    name: int
      #  rules:
      #    - if: '$CI_COMMIT_BRANCH == "develop"'
