variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  VERSIONING_DISABLE: "false"
  VERSIONING_GIT_TAG: $CI_COMMIT_TAG
  VERSIONING_GIT_BRANCH: $CI_COMMIT_BRANCH

default:
  cache:
    paths:
      - .m2/repository/
  tags:
    - qlf-ci.inria.fr

stages:
  - build
  - integration-tests

build:
  image: maven:3.6.3-adoptopenjdk-11
  stage: build
  script:
    - mvn -B -s .mvn/settings-ci.xml -ntp -fae -DdeployAtEnd deploy
  artifacts:
    paths:
      - "**/target/*.jar"
    reports:
      junit:
        - "**/target/surefire-reports/TEST-*.xml"

integration-tests:
  image: registry.gitlab.inria.fr/stemcovid19/tac-server/docker-image/tac-system-tests:latest
  stage: integration-tests
  before_script:
    - export PATH="$PWD/docker-compose:$PATH"
    - export CLEA_ROOT_DIR=$CI_PROJECT_DIR
    - export ENDPOINT_OUTSCALE="http://minio:9000"
  script:
    - currentContainer=$(basename $(cat /proc/1/cpuset))
    - docker-compose up -d
    - docker network connect clea-server_default $currentContainer
    - echo "Waiting for clea-ws-rest component to be up..."
    - until curl -s http://clea-ws-rest:8080/actuator/health | grep -q UP; do sleep 0.5; done;
    - java -jar -Dspring.profiles.active=docker clea-integration-tests/target/*-SNAPSHOT.jar
    - docker network disconnect clea-server_default $currentContainer
    - docker-compose down
  artifacts:
      paths:
        - "$CI_PROJECT_DIR/cucumber-reports.html"
      expire_in: 2 weeks