variables:
  ANSIBLE_DEPLOY_PROJECT: clea/clea-ansible

include:
  - project: stopcovid19/accueil
    file: gitlab/gitlab-ci-java-template.yml

e2e-tests-docker:
  script:
    - java -jar -Dspring.profiles.active=docker clea-integration-tests/target/clea-integration-tests-*.jar
