include:
  - project: stopcovid19/accueil
    ref: master
    file: gitlab/gitlab-ci-java-template.yml

build:
  script:
    - echo skip

quality:
  script:
    - echo skip

e2e-tests-docker:
  script:
    - docker ps
    - ping -c1 minion
    - java -jar -Dspring.profiles.active=docker clea-integration-tests/target/clea-integration-tests-*.jar
