include:
  - project: stopcovid19/accueil
    ref: master
    file: gitlab/gitlab-ci-java-template.yml

build:
  script:
    - mvn -B -s .mvn/settings-ci.xml deploy -DskipTests=true

e2e-tests-docker:
  script:
    - docker ps
    - docker logs clea-server_minio_1
    - java -jar -Dspring.profiles.active=docker clea-integration-tests/target/clea-integration-tests-*.jar

deploy-int:
  stage: deploy
  variables:
    APP_VERSION: develop-SNAPSHOT
  trigger:
    project: stemcovid19/infrastructure/functional-zone/services/clea/clea-ansible
    branch: master
    strategy: depend
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
