integration-tests:
  ws-rest.base-url: http://10.0.21.5:8088
  venue-consumer:
    base-url: http://10.0.21.50:8089
    management-url: http://10.0.21.50:8081
  batch:
    command: "sudo systemctl restart clea-batch.service"
  bucket:
    url: https://oos.eu-west-2.outscale.com
    name: signal-static-int
