integration-tests:
  ws-rest.base-url: http://clea-ws-rest:8080
  venue-consumer:
    base-url: http://clea-venue-consumer:8080
    management-url: http://clea-venue-consumer:8081
  batch.command: "docker-compose up clea-batch"
  bucket:
    url: http://minio:9000

spring.elasticsearch.rest:
  username: elastic
  password: password
  uris: http://elasticsearch:9200
