integration-tests:
  ws-rest.base-url: http://localhost:8080
  venue-consumer.base-url: http://localhost:7070
  batch.command: "docker-compose up clea-batch"
  bucket:
    url: http://localhost:9000
    access-key: AKIAIOSFODNN7EXAMPLE
    secret-key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

spring.elasticsearch.rest:
  username: elastic
  password: password
  uris: http://localhost:9200
