integration-tests:
  ws-rest.base-url: http://clea-ws-rest:8080
  venue-consumer.base-url: http://clea-venue-consumer:7070
  batch.command: "docker-compose up clea-batch"
  bucket:
    url: http://minio:9000
    access-key: AKIAIOSFODNN7EXAMPLE
    secret-key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

spring.elasticsearch.rest:
  username: elastic
  password: password
  uris: http://elasticsearch:9200
