openapi: 3.0.3
info:
  title: Tous AntiCovid Cluster Exposure Verification (Cléa)
  description: "#TOUSANTICOVID, Cléa API"
  contact:
    email: stopcovid@inria.fr
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 2.0.0
tags:
  - name: clea
    description: Clea API
paths:
  "/api/v2/wreport":
    post:
      tags:
        - noValidation
      summary: Upload locations history
      operationId: wreport
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/ReportRequest"
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ReportResponse"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
        "401":
          description: Invalid authentication
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
        "500":
          description: Internal error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
  "/api/v2/manual-report":
    post:
      summary: Manually upload locations history
      description: Pivot date for the whole list is automatically set to 1 hour before oldest visit of the list
      operationId: manualReport
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/ManualReportRequest"
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ReportResponse"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
        "401":
          description: Invalid authentication
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
        "500":
          description: Internal error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
components:
  schemas:
    ReportRequest:
      required:
        - visits
        - pivotDate
      type: object
      properties:
        pivotDate:
          type: integer
          format: int64
          description: An estimate date of contamination
        visits:
          type: array
          items:
            "$ref": "#/components/schemas/Visit"
    ManualReportRequest:
      required:
        - visits
      type: object
      properties:
        visits:
          type: array
          items:
            "$ref": "#/components/schemas/Visit"
    ReportResponse:
      type: object
      properties:
        accepted:
          type: integer
          format: int64
        rejected:
          type: integer
          format: int64
      required:
        - accepted
        - rejected
    ErrorResponse:
      title: ErrorResponse
      type: object
      properties:
        message:
          type: string
        validationErrors:
          type: array
          items:
            "$ref": "#/components/schemas/ValidationError"
      required:
        - message
        - validationErrors
    Visit:
      type: object
      properties:
        encryptedLocationSpecificPart:
          type: string
          description: Encrypted location specific part encoded in Base64
        scanTime:
          type: integer
          format: int64
          description: ISO 8601 timestamp when a user terminal scans a given QR code
      required:
        - encryptedLocationSpecificPart
        - scanTime
    ValidationError:
      title: Validation error
      type: object
      properties:
        object:
          type: string
        field:
          type: string
        rejectedValue:
          type: object
        message:
          type: string
